server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api
  retryable: true
  routes:
    item-service: /item/**  #将商品微服务映射到 /api/item/**
ribbon:
  ConnectTimeout: 6000 # 连接超时时间(ms)
  ReadTimeout: 6000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 15000 # 熔断超时时长：10000ms
